Deactivate
mozilla/oneanddone pull request #365
Opened 2016-10-31 15:09 UTC by rbillings

2016-10-31 15:17 UTC, rbillings commented
Please review @karlht , @stephendonner - checks have failed because it tried to run tests on deleted files.

2016-10-31 17:21 UTC, stephendonner commented on README.md
> +This repository holds code and automation that were used for Mozilla's [One and Done](https://oneanddone.mozilla.org/) website.
Should this be "This repository held code"?

2016-10-31 17:25 UTC, stephendonner commented
While I've removed the Travis-CI integration/webhook, we'll still need to 1) push another change to the repo (assuming that'll obviate the former "required-status check"? and/or 2) change the repo in GitHub to not require that former status check.

Looking into it still.

2016-10-31 17:27 UTC, rbillings commented on README.md
> +This repository holds code and automation that were used for Mozilla's [One and Done](https://oneanddone.mozilla.org/) website.
I don't think so as the code is still there - you just have to look for it.

2016-10-31 17:28 UTC, rbillings commented on README.md
> +This repository holds code and automation that were used for Mozilla's [One and Done](https://oneanddone.mozilla.org/) website.
Also, it was written to match https://github.com/mozilla/moz-grid-config/pull/161/files

2016-10-31 17:29 UTC, rbillings commented
@stephendonner - do we really need to make those changes for Travis as no more code will ever be pushed?

2016-10-31 17:32 UTC, stephendonner commented
@rbillings with the way it was set up, I believe so.  I was thinking we should remove the https://github.com/rbillings/oneanddone/blob/ff64f1886e648839b70c6af43fb25b14eda1759c/.travis.yml file.  Might be good for @karlht @bobsilverberg @davehunt to weigh in.  My past decommissions of projects have removed every file from the repo, leaving only the README as a pointer to why, so not sure if we should be doing the same here?

2016-10-31 17:35 UTC, stephendonner commented
e.g. https://github.com/mozilla/marketplace-tests/pull/761 and from @justinpotts ' https://github.com/mozilla/Affiliates-Tests/pull/139

2016-10-31 17:56 UTC, rbillings commented
I removed all of the files beginning with "." that I missed on the first round.

2016-10-31 19:14 UTC, stephendonner commented
For posterity, I also disabled the requirement that the master branch have a passing Travis CI build before merging pulls, which is no longer possible, given the nature of the changes (code removal).

<img width="1786" alt="screen shot 2016-10-31 at 12 08 03 pm" src="https://cloud.githubusercontent.com/assets/387249/19868040/960fbc6c-9f63-11e6-9d67-15f6471fab80.png">

2016-10-31 19:19 UTC, stephendonner requested changes
Thanks, @rbillings - these changes look good to me, but I think you can probably also remove .gitignore.

2016-10-31 19:20 UTC, stephendonner commented
(And let me know if you need help with any of the steps in https://wiki.mozilla.org/QA/Execution/Web_Testing/Repositories#Deactivating_a_repository.)

2016-10-31 21:22 UTC, rbillings commented
Removed the last sneaky .gitignore file.

2016-10-31 23:34 UTC, stephendonner approved these changes

2016-10-31 23:35 UTC, stephendonner commented
Thanks; r+ - leaving open to give @karlht an opportunity to r+/merge, etc.

2016-11-01 00:13 UTC, karlht commented
@stephendonner This looks fine to me -- you may have the honours.  Merge at will.

2016-11-01 00:15 UTC, merged